from datetime import UTC, datetime

from app.services.experimental_linkedin_capture.models import ExperimentalCaptureDiagnostic


EXP_CAPTURE_DISABLED = "EXP_CAPTURE_DISABLED"
EXP_CAPTURE_STARTED = "EXP_CAPTURE_STARTED"
EXP_CAPTURE_STOPPED = "EXP_CAPTURE_STOPPED"
EXP_LEFT_PANEL_NOT_FOUND = "EXP_LEFT_PANEL_NOT_FOUND"
EXP_CARD_CLICK_ATTEMPTED = "EXP_CARD_CLICK_ATTEMPTED"
EXP_CARD_SELECTED = "EXP_CARD_SELECTED"
EXP_URL_CURRENT_JOB_ID_MATCHED = "EXP_URL_CURRENT_JOB_ID_MATCHED"
EXP_URL_CURRENT_JOB_ID_MISMATCH = "EXP_URL_CURRENT_JOB_ID_MISMATCH"
EXP_DETAIL_TEXT_READY = "EXP_DETAIL_TEXT_READY"
EXP_DETAIL_TEXT_STALE = "EXP_DETAIL_TEXT_STALE"
EXP_DUPLICATE_JOB_ID = "EXP_DUPLICATE_JOB_ID"
EXP_PAGE_LIMIT_REACHED = "EXP_PAGE_LIMIT_REACHED"
EXP_JOB_LIMIT_REACHED = "EXP_JOB_LIMIT_REACHED"
EXP_NEXT_PAGE_ATTEMPTED = "EXP_NEXT_PAGE_ATTEMPTED"
EXP_NEXT_PAGE_NOT_FOUND = "EXP_NEXT_PAGE_NOT_FOUND"
EXP_CAPTURE_COMPLETED = "EXP_CAPTURE_COMPLETED"
EXP_CAPTURE_FAILED = "EXP_CAPTURE_FAILED"
EXP_SELECTED_JOB_CAPTURE_STARTED = "EXP_SELECTED_JOB_CAPTURE_STARTED"
EXP_BROWSER_URL_CAPTURED = "EXP_BROWSER_URL_CAPTURED"
EXP_CURRENT_JOB_ID_EXTRACTED = "EXP_CURRENT_JOB_ID_EXTRACTED"
EXP_CURRENT_JOB_ID_MISSING = "EXP_CURRENT_JOB_ID_MISSING"
EXP_VISIBLE_TEXT_CAPTURED = "EXP_VISIBLE_TEXT_CAPTURED"
EXP_VISIBLE_TEXT_TOO_SHORT = "EXP_VISIBLE_TEXT_TOO_SHORT"
EXP_DETAIL_TEXT_NOT_READY = "EXP_DETAIL_TEXT_NOT_READY"
EXP_SELECTED_JOB_CAPTURE_COMPLETED = "EXP_SELECTED_JOB_CAPTURE_COMPLETED"
EXP_SELECTED_JOB_CAPTURE_FAILED = "EXP_SELECTED_JOB_CAPTURE_FAILED"
EXP_SELECTED_JOB_ADAPTER_DEPENDENCY_MISSING = "EXP_SELECTED_JOB_ADAPTER_DEPENDENCY_MISSING"
EXP_FOCUS_HANDOFF_STARTED = "EXP_FOCUS_HANDOFF_STARTED"
EXP_FOCUS_HANDOFF_WAITING = "EXP_FOCUS_HANDOFF_WAITING"
EXP_FOCUS_HANDOFF_COMPLETED = "EXP_FOCUS_HANDOFF_COMPLETED"
EXP_FOCUSED_WINDOW_CAPTURE_STARTED = "EXP_FOCUSED_WINDOW_CAPTURE_STARTED"
EXP_FOCUSED_WINDOW_CAPTURE_FAILED = "EXP_FOCUSED_WINDOW_CAPTURE_FAILED"
EXP_NON_LINKEDIN_URL_CAPTURED = "EXP_NON_LINKEDIN_URL_CAPTURED"
EXP_LEGACY_BATCH_CAPTURE_STARTED = "EXP_LEGACY_BATCH_CAPTURE_STARTED"
EXP_LEGACY_BATCH_CAPTURE_COMPLETED = "EXP_LEGACY_BATCH_CAPTURE_COMPLETED"
EXP_LEGACY_BATCH_CAPTURE_FAILED = "EXP_LEGACY_BATCH_CAPTURE_FAILED"
EXP_LEGACY_BATCH_DEPENDENCIES_OK = "EXP_LEGACY_BATCH_DEPENDENCIES_OK"
EXP_LEGACY_BATCH_DEPENDENCIES_MISSING = "EXP_LEGACY_BATCH_DEPENDENCIES_MISSING"
EXP_ACTIVE_WINDOW_CAPTURED = "EXP_ACTIVE_WINDOW_CAPTURED"
EXP_ACTIVE_WINDOW_TITLE_CAPTURED = "EXP_ACTIVE_WINDOW_TITLE_CAPTURED"
EXP_SCREENSHOT_CAPTURE_STARTED = "EXP_SCREENSHOT_CAPTURE_STARTED"
EXP_SCREENSHOT_CAPTURED = "EXP_SCREENSHOT_CAPTURED"
EXP_CARD_DETECTION_STARTED = "EXP_CARD_DETECTION_STARTED"
EXP_CARD_DETECTION_COMPLETED = "EXP_CARD_DETECTION_COMPLETED"
EXP_CARD_DETECTION_ZERO_CARDS = "EXP_CARD_DETECTION_ZERO_CARDS"
EXP_CARD_CANDIDATES_LISTED = "EXP_CARD_CANDIDATES_LISTED"
EXP_CARD_CLICK_SEQUENCE_STARTED = "EXP_CARD_CLICK_SEQUENCE_STARTED"
EXP_LEGACY_CARD_DETECTED = "EXP_LEGACY_CARD_DETECTED"
EXP_LEGACY_CARD_CLICK_SKIPPED = "EXP_LEGACY_CARD_CLICK_SKIPPED"
EXP_CARD_CLICK_COMPLETED = "EXP_CARD_CLICK_COMPLETED"
EXP_BROWSER_URL_CAPTURE_STARTED = "EXP_BROWSER_URL_CAPTURE_STARTED"
EXP_DETAIL_TEXT_CAPTURE_STARTED = "EXP_DETAIL_TEXT_CAPTURE_STARTED"
EXP_DETAIL_TEXT_CAPTURED = "EXP_DETAIL_TEXT_CAPTURED"
EXP_DETAIL_TEXT_TOO_SHORT = "EXP_DETAIL_TEXT_TOO_SHORT"
EXP_DETAIL_TEXT_EQUALS_URL = "EXP_DETAIL_TEXT_EQUALS_URL"
EXP_LEFT_PANEL_SCROLL_STARTED = "EXP_LEFT_PANEL_SCROLL_STARTED"
EXP_LEFT_PANEL_SCROLL_COMPLETED = "EXP_LEFT_PANEL_SCROLL_COMPLETED"
EXP_LEFT_PANEL_SCROLL_NO_MOVEMENT = "EXP_LEFT_PANEL_SCROLL_NO_MOVEMENT"
EXP_MOUSE_CONTROL_TEST_STARTED = "EXP_MOUSE_CONTROL_TEST_STARTED"
EXP_MOUSE_CONTROL_DEPENDENCIES_OK = "EXP_MOUSE_CONTROL_DEPENDENCIES_OK"
EXP_MOUSE_CONTROL_DEPENDENCIES_MISSING = "EXP_MOUSE_CONTROL_DEPENDENCIES_MISSING"
EXP_MOUSE_POSITION_CAPTURED = "EXP_MOUSE_POSITION_CAPTURED"
EXP_SCREEN_SIZE_CAPTURED = "EXP_SCREEN_SIZE_CAPTURED"
EXP_MOUSE_MOVEMENT_ATTEMPTED = "EXP_MOUSE_MOVEMENT_ATTEMPTED"
EXP_MOUSE_MOVEMENT_COMPLETED = "EXP_MOUSE_MOVEMENT_COMPLETED"
EXP_MOUSE_MOVEMENT_FAILED = "EXP_MOUSE_MOVEMENT_FAILED"
EXP_LEGACY_SCROLL_ATTEMPTED = "EXP_LEGACY_SCROLL_ATTEMPTED"
EXP_LEGACY_SCROLL_COMPLETED = "EXP_LEGACY_SCROLL_COMPLETED"
EXP_LEGACY_PAGE_TRANSITION_ATTEMPTED = "EXP_LEGACY_PAGE_TRANSITION_ATTEMPTED"
EXP_LEGACY_PAGE_TRANSITION_COMPLETED = "EXP_LEGACY_PAGE_TRANSITION_COMPLETED"
EXP_LEGACY_PACKAGE_WRITTEN = "EXP_LEGACY_PACKAGE_WRITTEN"

EXPERIMENTAL_CAPTURE_CODES = [
    EXP_CAPTURE_DISABLED,
    EXP_CAPTURE_STARTED,
    EXP_CAPTURE_STOPPED,
    EXP_LEFT_PANEL_NOT_FOUND,
    EXP_CARD_CLICK_ATTEMPTED,
    EXP_CARD_SELECTED,
    EXP_URL_CURRENT_JOB_ID_MATCHED,
    EXP_URL_CURRENT_JOB_ID_MISMATCH,
    EXP_DETAIL_TEXT_READY,
    EXP_DETAIL_TEXT_STALE,
    EXP_DUPLICATE_JOB_ID,
    EXP_PAGE_LIMIT_REACHED,
    EXP_JOB_LIMIT_REACHED,
    EXP_NEXT_PAGE_ATTEMPTED,
    EXP_NEXT_PAGE_NOT_FOUND,
    EXP_CAPTURE_COMPLETED,
    EXP_CAPTURE_FAILED,
    EXP_SELECTED_JOB_CAPTURE_STARTED,
    EXP_BROWSER_URL_CAPTURED,
    EXP_CURRENT_JOB_ID_EXTRACTED,
    EXP_CURRENT_JOB_ID_MISSING,
    EXP_VISIBLE_TEXT_CAPTURED,
    EXP_VISIBLE_TEXT_TOO_SHORT,
    EXP_DETAIL_TEXT_NOT_READY,
    EXP_SELECTED_JOB_CAPTURE_COMPLETED,
    EXP_SELECTED_JOB_CAPTURE_FAILED,
    EXP_SELECTED_JOB_ADAPTER_DEPENDENCY_MISSING,
    EXP_FOCUS_HANDOFF_STARTED,
    EXP_FOCUS_HANDOFF_WAITING,
    EXP_FOCUS_HANDOFF_COMPLETED,
    EXP_FOCUSED_WINDOW_CAPTURE_STARTED,
    EXP_FOCUSED_WINDOW_CAPTURE_FAILED,
    EXP_NON_LINKEDIN_URL_CAPTURED,
    EXP_LEGACY_BATCH_CAPTURE_STARTED,
    EXP_LEGACY_BATCH_CAPTURE_COMPLETED,
    EXP_LEGACY_BATCH_CAPTURE_FAILED,
    EXP_LEGACY_BATCH_DEPENDENCIES_OK,
    EXP_LEGACY_BATCH_DEPENDENCIES_MISSING,
    EXP_ACTIVE_WINDOW_CAPTURED,
    EXP_ACTIVE_WINDOW_TITLE_CAPTURED,
    EXP_SCREENSHOT_CAPTURE_STARTED,
    EXP_SCREENSHOT_CAPTURED,
    EXP_CARD_DETECTION_STARTED,
    EXP_CARD_DETECTION_COMPLETED,
    EXP_CARD_DETECTION_ZERO_CARDS,
    EXP_CARD_CANDIDATES_LISTED,
    EXP_CARD_CLICK_SEQUENCE_STARTED,
    EXP_LEGACY_CARD_DETECTED,
    EXP_LEGACY_CARD_CLICK_SKIPPED,
    EXP_CARD_CLICK_COMPLETED,
    EXP_BROWSER_URL_CAPTURE_STARTED,
    EXP_DETAIL_TEXT_CAPTURE_STARTED,
    EXP_DETAIL_TEXT_CAPTURED,
    EXP_DETAIL_TEXT_TOO_SHORT,
    EXP_DETAIL_TEXT_EQUALS_URL,
    EXP_LEFT_PANEL_SCROLL_STARTED,
    EXP_LEFT_PANEL_SCROLL_COMPLETED,
    EXP_LEFT_PANEL_SCROLL_NO_MOVEMENT,
    EXP_MOUSE_CONTROL_TEST_STARTED,
    EXP_MOUSE_CONTROL_DEPENDENCIES_OK,
    EXP_MOUSE_CONTROL_DEPENDENCIES_MISSING,
    EXP_MOUSE_POSITION_CAPTURED,
    EXP_SCREEN_SIZE_CAPTURED,
    EXP_MOUSE_MOVEMENT_ATTEMPTED,
    EXP_MOUSE_MOVEMENT_COMPLETED,
    EXP_MOUSE_MOVEMENT_FAILED,
    EXP_LEGACY_SCROLL_ATTEMPTED,
    EXP_LEGACY_SCROLL_COMPLETED,
    EXP_LEGACY_PAGE_TRANSITION_ATTEMPTED,
    EXP_LEGACY_PAGE_TRANSITION_COMPLETED,
    EXP_LEGACY_PACKAGE_WRITTEN,
]


def utc_now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def diagnostic_event(
    code: str,
    message: str,
    *,
    level: str = "info",
    details: dict[str, str | int | bool | None] | None = None,
) -> ExperimentalCaptureDiagnostic:
    return ExperimentalCaptureDiagnostic(
        code=code,
        message=message,
        level=level,  # type: ignore[arg-type]
        timestamp=utc_now_iso(),
        details=details or {},
    )
